using System.Media;
using System.IO;
using System.Diagnostics;
using System.Windows;
using System.Windows.Input;
using Microsoft.Win32;
using FocusPocus.Engine.Models;
using FocusPocus.Engine.Views;
using Forms = System.Windows.Forms;

namespace FocusPocus.Engine.Services;

public sealed class AppController : IDisposable
{
    private readonly SettingsService _storage=new(); private readonly InputHookService _hooks=new(); private readonly System.Windows.Threading.DispatcherTimer _syncTimer=new(){Interval=TimeSpan.FromMilliseconds(400)}; private OverlayWindow _overlay=null!; private Forms.NotifyIcon _tray=null!; private Forms.ToolStripMenuItem _showMenuItem=null!,_spotlightMenuItem=null!,_clicksMenuItem=null!,_keysMenuItem=null!,_exitMenuItem=null!; private DateTime _settingsWriteTimeUtc;
    public AppSettings Settings{get;private set;}=null!; public Localizer Localizer{get;private set;}=null!; public bool IsExiting{get;private set;}
    public void Start(bool startInTray=false){Settings=_storage.Load();Localizer=new(Settings.Language);SetStartup(Settings.StartWithWindows);FocusPocus.Engine.Interop.NativeMethods.GetCursorPos(out var p);_overlay=new OverlayWindow(Settings,Forms.Screen.FromPoint(new System.Drawing.Point(p.X,p.Y)));_hooks.MouseClicked+=OnClick;_hooks.KeyPressed+=OnKey;_hooks.Start();CreateTray();ApplyLive();_settingsWriteTimeUtc=File.Exists(_storage.SettingsPath)?File.GetLastWriteTimeUtc(_storage.SettingsPath):DateTime.MinValue;_syncTimer.Tick+=(_,_)=>SyncExternalState();_syncTimer.Start();}
    private void SyncExternalState(){var writeTime=File.Exists(_storage.SettingsPath)?File.GetLastWriteTimeUtc(_storage.SettingsPath):DateTime.MinValue;if(writeTime!=DateTime.MinValue&&writeTime!=_settingsWriteTimeUtc){Settings=_storage.Load();Localizer.Language=Settings.Language;_settingsWriteTimeUtc=writeTime;SetStartup(Settings.StartWithWindows);ApplyLive();RefreshTray();}var uiVisible=Process.GetProcessesByName("FocusPocus").Any();_overlay.Topmost=!uiVisible;}
    public void ApplyLive(){try{_overlay.ApplySettings(Settings);_overlay.SetSpotlight(Settings.SpotlightEnabled);}catch{} }
    private void OnClick(bool left,int x,int y)=>System.Windows.Application.Current.Dispatcher.Invoke(()=>{if(!Settings.ClicksEnabled)return;_overlay.MoveToScreen(Forms.Screen.FromPoint(new System.Drawing.Point(x,y)));_overlay.ShowClick(left,x,y,left?Settings.LeftClickColor:Settings.RightClickColor);if(Settings.ClickSoundEnabled)SystemSounds.Asterisk.Play();});
    private void OnKey(Key key,ModifierKeys mods)=>System.Windows.Application.Current.Dispatcher.Invoke(()=>{var text=HotkeyService.Format(mods,key);if(Matches(text,Settings.SpotlightHotkey)){ToggleSpotlight();return;}if(Matches(text,Settings.ClicksHotkey)){ToggleClicks();return;}if(Matches(text,Settings.KeystrokesHotkey)){ToggleKeystrokes();return;}if(Matches(text,Settings.IncreaseSpotSizeHotkey)){ChangeSpotSize(10);return;}if(Matches(text,Settings.DecreaseSpotSizeHotkey)){ChangeSpotSize(-10);return;}if(Matches(text,Settings.DecreaseOverlayOpacityHotkey)){ChangeOverlayOpacity(-10);return;}if(Matches(text,Settings.IncreaseOverlayOpacityHotkey)){ChangeOverlayOpacity(10);return;}if(Settings.KeystrokesEnabled&&(!Settings.ShowShortcutsOnly||mods!=ModifierKeys.None)&&!IsPasswordField())_overlay.ShowKey(text);});
    private void ToggleSpotlight(){Settings.SpotlightEnabled=!Settings.SpotlightEnabled;ApplyLive();SaveSettings();RefreshTray();}
    private void ToggleClicks(){Settings.ClicksEnabled=!Settings.ClicksEnabled;SaveSettings();RefreshTray();}
    private void ToggleKeystrokes(){Settings.KeystrokesEnabled=!Settings.KeystrokesEnabled;SaveSettings();RefreshTray();}
    private void ChangeSpotSize(double percentagePoints){const double minimum=100,maximum=800;var change=(maximum-minimum)*percentagePoints/100;Settings.SpotDiameter=Math.Clamp(Settings.SpotDiameter+change,minimum,maximum);ApplyLive();SaveSettings();}
    private void ChangeOverlayOpacity(double percentagePoints){Settings.OverlayOpacityPercent=Math.Clamp(Settings.OverlayOpacityPercent+percentagePoints,0,100);ApplyLive();SaveSettings();}
    private static bool Matches(string a,string b)=>string.Equals(a,b,StringComparison.OrdinalIgnoreCase);
    private static bool IsPasswordField(){var hwnd=FocusPocus.Engine.Interop.NativeMethods.GetForegroundWindow();var thread=FocusPocus.Engine.Interop.NativeMethods.GetWindowThreadProcessId(hwnd,out _);var info=new FocusPocus.Engine.Interop.NativeMethods.GuiThreadInfo{Size=System.Runtime.InteropServices.Marshal.SizeOf<FocusPocus.Engine.Interop.NativeMethods.GuiThreadInfo>()};if(!FocusPocus.Engine.Interop.NativeMethods.GetGUIThreadInfo(thread,ref info)||info.Focus==0)return false;var style=FocusPocus.Engine.Interop.NativeMethods.GetWindowLongPtr(info.Focus,FocusPocus.Engine.Interop.NativeMethods.GWL_STYLE).ToInt64();return(style&FocusPocus.Engine.Interop.NativeMethods.ES_PASSWORD)!=0;}
    public bool ValidateAndSave(out string error){error="";try{_ = System.Windows.Media.ColorConverter.ConvertFromString(Settings.OverlayColor);}catch{error=Localizer["InvalidColor"];return false;}var h=new[]{Settings.SpotlightHotkey,Settings.ClicksHotkey,Settings.KeystrokesHotkey,Settings.IncreaseSpotSizeHotkey,Settings.DecreaseSpotSizeHotkey,Settings.DecreaseOverlayOpacityHotkey,Settings.IncreaseOverlayOpacityHotkey};if(h.Distinct(StringComparer.OrdinalIgnoreCase).Count()!=h.Length||h.Any(x=>!HotkeyService.TryParse(x,out _,out _))){error=Localizer["ShortcutConflict"];return false;}SetStartup(Settings.StartWithWindows);SaveSettings();ApplyLive();return true;}
    private void SaveSettings(){_storage.Save(Settings);_settingsWriteTimeUtc=File.GetLastWriteTimeUtc(_storage.SettingsPath);}
    private static void SetStartup(bool enabled){using var key=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run",true);if(enabled)key?.SetValue("FocusPocus",$"\"{Environment.ProcessPath}\" --tray");else key?.DeleteValue("FocusPocus",false);}
    private void CreateTray(){var iconPath=Path.Combine(AppContext.BaseDirectory,"Assets","FocusPocus.ico");_tray=new Forms.NotifyIcon{Text="FocusPocus",Icon=File.Exists(iconPath)?new System.Drawing.Icon(iconPath):System.Drawing.SystemIcons.Information,Visible=true};_tray.DoubleClick+=(_,_)=>ShowMain();var menu=new Forms.ContextMenuStrip();_showMenuItem=new Forms.ToolStripMenuItem();_showMenuItem.Click+=(_,_)=>ShowMain();_spotlightMenuItem=new Forms.ToolStripMenuItem();_spotlightMenuItem.Click+=(_,_)=>ToggleSpotlight();_clicksMenuItem=new Forms.ToolStripMenuItem();_clicksMenuItem.Click+=(_,_)=>ToggleClicks();_keysMenuItem=new Forms.ToolStripMenuItem();_keysMenuItem.Click+=(_,_)=>ToggleKeystrokes();_exitMenuItem=new Forms.ToolStripMenuItem();_exitMenuItem.Click+=(_,_)=>Exit();menu.Items.AddRange(new Forms.ToolStripItem[]{_showMenuItem,new Forms.ToolStripSeparator(),_spotlightMenuItem,_clicksMenuItem,_keysMenuItem,new Forms.ToolStripSeparator(),_exitMenuItem});_tray.ContextMenuStrip=menu;RefreshTray();}
    public void RefreshTray(){if(_tray==null)return;_showMenuItem.Text=Localizer["Show"];_spotlightMenuItem.Text=Localizer["ToggleSpotlight"];_spotlightMenuItem.Checked=Settings.SpotlightEnabled;_clicksMenuItem.Text=Localizer["ToggleClicks"];_clicksMenuItem.Checked=Settings.ClicksEnabled;_keysMenuItem.Text=Localizer["ToggleKeys"];_keysMenuItem.Checked=Settings.KeystrokesEnabled;_exitMenuItem.Text=Localizer["Exit"];}
    private void ShowMain(){var uiPath=Path.Combine(AppContext.BaseDirectory,"FocusPocus.exe");if(File.Exists(uiPath))Process.Start(new ProcessStartInfo(uiPath){UseShellExecute=true});}
    private void Exit(){IsExiting=true;SaveSettings();System.Windows.Application.Current.Shutdown();}
    public void Dispose(){_syncTimer.Stop();_hooks.Dispose();if(_tray!=null){_tray.Visible=false;_tray.Dispose();}}
}
