<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>FocusPocus</RootNamespace>
    <AssemblyName>FocusPocus</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\FocusPocus.Engine\Assets\FocusPocus.ico</ApplicationIcon>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>2.1.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250907003" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\FocusPocus.Engine\Assets\FocusPocus.png" Link="Assets\FocusPocus.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\FocusPocus.Engine\Assets\FocusPocus.ico" Link="Assets\FocusPocus.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="CopyApplicationPriToPublish" AfterTargets="Publish">
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).pri" DestinationFolder="$(PublishDir)" Condition="Exists('$(TargetDir)$(AssemblyName).pri')" />
  </Target>
</Project>
