using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using SpotDot.Models;
using SpotDot.Services;
using System.Windows.Interop;
using SpotDot.Interop;
using Forms = System.Windows.Forms;

namespace SpotDot.Views;

public partial class MainWindow : Wpf.Ui.Controls.FluentWindow
{
    private readonly AppController _controller; private AppSettings S => _controller.Settings; private Localizer L => _controller.Localizer; private bool _loading = true;
    public MainWindow(AppController controller) { _controller=controller; InitializeComponent(); LoadValues(); Closing += OnClosing; Loaded += CenterOnCursorScreen; }
    private void CenterOnCursorScreen(object sender,RoutedEventArgs e){NativeMethods.GetCursorPos(out var p);var screen=Forms.Screen.FromPoint(new System.Drawing.Point(p.X,p.Y));var hwnd=new WindowInteropHelper(this).Handle;if(hwnd==0||!NativeMethods.GetWindowRect(hwnd,out var r))return;var width=r.Right-r.Left;var height=r.Bottom-r.Top;var area=screen.WorkingArea;var x=area.Left+Math.Max(0,(area.Width-width)/2);var y=area.Top+Math.Max(0,(area.Height-height)/2);NativeMethods.SetWindowPos(hwnd,0,x,y,width,height,NativeMethods.SWP_NOACTIVATE);Loaded-=CenterOnCursorScreen;}
    private void LoadValues(){_loading=true; SpotEnabled.IsChecked=S.SpotlightEnabled;ClicksEnabled.IsChecked=S.ClicksEnabled;KeysEnabled.IsChecked=S.KeystrokesEnabled;ShortcutsOnly.IsChecked=S.ShowShortcutsOnly;SoundEnabled.IsChecked=S.ClickSoundEnabled;StartupEnabled.IsChecked=S.StartWithWindows;TrayEnabled.IsChecked=S.MinimizeToTray;SizeSlider.Value=S.SpotDiameter;FeatherSlider.Value=S.FeatherSize;KeySizeSlider.Value=S.KeystrokeFontSize;OpacitySlider.Value=S.OverlayOpacityPercent;UpdateSliderDisplays();ColorBox.Text=S.OverlayColor;UpdateColorPreview();SpotShortcut.Text=S.SpotlightHotkey;ClickShortcut.Text=S.ClicksHotkey;KeyShortcut.Text=S.KeystrokesHotkey;IncreaseSpotSizeShortcut.Text=S.IncreaseSpotSizeHotkey;DecreaseSpotSizeShortcut.Text=S.DecreaseSpotSizeHotkey;DecreaseOverlayOpacityShortcut.Text=S.DecreaseOverlayOpacityHotkey;IncreaseOverlayOpacityShortcut.Text=S.IncreaseOverlayOpacityHotkey;LanguageBox.SelectedIndex=S.Language=="en"?1:0; Translate();_loading=false;}
    private void Translate(){Subtitle.Text=L["AppSubtitle"];PageTitle.Text=L["Spotlight"];SpotEnabled.Content=L["EnableSpotlight"];SizeLabel.Text=L["SpotSize"];FeatherLabel.Text=L["Feather"];ColorLabel.Text=L["OverlayColor"];ColorPickerButton.Content=L["ChooseColor"];OpacityLabel.Text=L["Opacity"];EffectsTitle.Text=L["InputEffects"];ClicksEnabled.Content=L["ShowClicks"];KeysEnabled.Content=L["ShowKeys"];ShortcutsOnly.Content=L["ShowShortcutsOnly"];SoundEnabled.Content=L["ClickSound"];KeySizeLabel.Text=L["KeySize"];PrivacyText.Text=L["PrivacyHint"];ShortcutsTitle.Text=L["Shortcuts"];SpotShortcutLabel.Text=L["ToggleSpotlight"];ClickShortcutLabel.Text=L["ToggleClicks"];KeyShortcutLabel.Text=L["ToggleKeys"];IncreaseSpotSizeShortcutLabel.Text=L["IncreaseSpotSize"];DecreaseSpotSizeShortcutLabel.Text=L["DecreaseSpotSize"];DecreaseOverlayOpacityShortcutLabel.Text=L["DecreaseOverlayOpacity"];IncreaseOverlayOpacityShortcutLabel.Text=L["IncreaseOverlayOpacity"];BehaviorTitle.Text=L["Behavior"];StartupEnabled.Content=L["StartWindows"];TrayEnabled.Content=L["Tray"];NavSpot.Content="◉   "+L["Spotlight"];NavInput.Content="⌁   "+L["InputEffects"];NavShortcuts.Content="⌨   "+L["Shortcuts"];NavSettings.Content="⚙   "+L["Behavior"];AboutButton.Content="ⓘ   "+L["About"];ApplyButton.Content=L["Apply"];}
    private void Pull(){S.SpotlightEnabled=SpotEnabled.IsChecked==true;S.ClicksEnabled=ClicksEnabled.IsChecked==true;S.KeystrokesEnabled=KeysEnabled.IsChecked==true;S.ShowShortcutsOnly=ShortcutsOnly.IsChecked==true;S.ClickSoundEnabled=SoundEnabled.IsChecked==true;S.StartWithWindows=StartupEnabled.IsChecked==true;S.MinimizeToTray=TrayEnabled.IsChecked==true;S.SpotDiameter=SizeSlider.Value;S.FeatherSize=FeatherSlider.Value;S.KeystrokeFontSize=KeySizeSlider.Value;S.OverlayOpacityPercent=OpacitySlider.Value;S.OverlayColor=ColorBox.Text;S.SpotlightHotkey=SpotShortcut.Text;S.ClicksHotkey=ClickShortcut.Text;S.KeystrokesHotkey=KeyShortcut.Text;S.IncreaseSpotSizeHotkey=IncreaseSpotSizeShortcut.Text;S.DecreaseSpotSizeHotkey=DecreaseSpotSizeShortcut.Text;S.DecreaseOverlayOpacityHotkey=DecreaseOverlayOpacityShortcut.Text;S.IncreaseOverlayOpacityHotkey=IncreaseOverlayOpacityShortcut.Text;}
    private void LiveChanged(object sender, RoutedEventArgs e){if(_loading)return;if(sender is Slider)UpdateSliderDisplays();if(sender==ColorBox)UpdateColorPreview();Pull();_controller.ApplyLive();}
    private static double SliderPercent(Slider slider)=>Math.Round((slider.Value-slider.Minimum)/(slider.Maximum-slider.Minimum)*100);
    private void UpdateSliderDisplays(){SizeValueLabel.Text=$"{Math.Round(SizeSlider.Value)} px · {SliderPercent(SizeSlider)}%";FeatherValueLabel.Text=$"{Math.Round(FeatherSlider.Value)} px · {SliderPercent(FeatherSlider)}%";KeySizeValueLabel.Text=$"{Math.Round(KeySizeSlider.Value)} pt · {SliderPercent(KeySizeSlider)}%";OpacityValueLabel.Text=$"{Math.Round(OpacitySlider.Value)}%";}
    private void UpdateColorPreview(){try{ColorPreview.Background=new System.Windows.Media.SolidColorBrush((System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString(ColorBox.Text));}catch{}}
    private void ChooseColorClicked(object sender,RoutedEventArgs e){System.Windows.Media.Color current;try{current=(System.Windows.Media.Color)System.Windows.Media.ColorConverter.ConvertFromString(ColorBox.Text);}catch{current=System.Windows.Media.Colors.Black;}using var dialog=new Forms.ColorDialog{FullOpen=true,AnyColor=true,Color=System.Drawing.Color.FromArgb(current.R,current.G,current.B)};if(dialog.ShowDialog()!=Forms.DialogResult.OK)return;ColorBox.Text=$"#{dialog.Color.R:X2}{dialog.Color.G:X2}{dialog.Color.B:X2}";}
    private void LanguageChanged(object sender, SelectionChangedEventArgs e){if(_loading||LanguageBox.SelectedItem is not ComboBoxItem i)return;S.Language=(string)i.Tag;L.Language=S.Language;Translate();_controller.RefreshTray();}
    private void CaptureShortcut(object sender, System.Windows.Input.KeyEventArgs e){e.Handled=true;var key=e.Key==Key.System?e.SystemKey:e.Key;if(key is Key.LeftCtrl or Key.RightCtrl or Key.LeftShift or Key.RightShift or Key.LeftAlt or Key.RightAlt or Key.LWin or Key.RWin)return;((System.Windows.Controls.TextBox)sender).Text=HotkeyService.Format(Keyboard.Modifiers,key);}
    private void ApplyClicked(object s,RoutedEventArgs e){Pull();if(!_controller.ValidateAndSave(out var error))new AlertWindow(error,L){Owner=this}.ShowDialog();}
    private void AboutClicked(object s,RoutedEventArgs e)=>new AboutWindow(L){Owner=this}.ShowDialog();
    public void UpdateSpotSize(double size){_loading=true;SizeSlider.Value=size;UpdateSliderDisplays();_loading=false;}
    public void UpdateOverlayOpacity(double opacity){_loading=true;OpacitySlider.Value=opacity;UpdateSliderDisplays();_loading=false;}
    private void TitleBarMouseDown(object sender,System.Windows.Input.MouseButtonEventArgs e){if(e.ChangedButton==MouseButton.Left&&e.ClickCount==1)DragMove();}
    private void ShowPage(FrameworkElement page,string title){SpotPage.Visibility=Visibility.Collapsed;InputPage.Visibility=Visibility.Collapsed;ShortcutsPage.Visibility=Visibility.Collapsed;SettingsPage.Visibility=Visibility.Collapsed;page.Visibility=Visibility.Visible;PageTitle.Text=title;}
    private void NavSpotClicked(object s,RoutedEventArgs e)=>ShowPage(SpotPage,L["Spotlight"]);
    private void NavInputClicked(object s,RoutedEventArgs e)=>ShowPage(InputPage,L["InputEffects"]);
    private void NavShortcutsClicked(object s,RoutedEventArgs e)=>ShowPage(ShortcutsPage,L["Shortcuts"]);
    private void NavSettingsClicked(object s,RoutedEventArgs e)=>ShowPage(SettingsPage,L["Behavior"]);
    private void OnClosing(object? s,System.ComponentModel.CancelEventArgs e){if(S.MinimizeToTray&&!_controller.IsExiting){e.Cancel=true;Hide();}}
}
