<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\FocusPocus.ico</ApplicationIcon>
    <AssemblyName>FocusPocus.Engine</AssemblyName>
    <RootNamespace>FocusPocus.Engine</RootNamespace>
    <Version>2.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\FocusPocus.ico" />
    <Content Include="Assets\FocusPocus.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
